apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  orgId: 1
  access: proxy
  basicAuth: false
  url: https://metric-store.sys.carmelbythesea.cf-app.com
  isDefault: true
  jsonData:
    keepCookies: []
    httpMethod: GET
    oauthPassThru: true
